;; This environment is configured for both linux and cygwin. Windows can't support symlinks, so
;; we have to work around that via variables.
(if (equal system-type 'windows-nt)
    (setq dotfiles-path "~/.dotfiles/emacs.d")
    (setq dotfiles-path "~/.emacs.d"))

(add-to-list 'load-path (concat dotfiles-path "/vendor"))

(load "config/theme")
(load "config/env")
(load "config/global")
(load "config/defuns")
(load "config/bindings")
(load "config/kbd-macros")
(load "config/tabs")
(load "config/disabled")
(load "config/fonts")
(load "config/utf-8")
(load "config/scratch")
(load "config/grep")
(load "config/diff")
;(load "config/ido") ; currently configured with flx instead
(load "config/dired")
(load "config/recentf")
(load "config/rectangle")
(load "config/org")
(load "config/zoom")
(load "config/flymake")
(load "config/javascript")
(load "config/ri-emacs")
(load "config/mac")
(load "config/server-mode")
(load "config/shell-mode")
(load "config/ruby-mode")
(load "config/c")
(load "config/saveplace")
(load "config/private" 'noerror)

;; (load "config/hl-line")
;; (load "config/iswitchb")

(vendor 'flx)
(vendor 'expand-region 'er/expand-region)
(vendor 'multiple-cursors 'mc/edit-lines 'mc/mark-next-like-this 'mc/mark-previous-like-this 'mc/mark-all-like-this 'set-rectangular-region-anchor)
(vendor 'jump-char     'jump-char-forward 'jump-char-backward)
(vendor 'rinari)
(vendor 'textmate)
(vendor 'maxframe      'mf 'maximize-frame)
(vendor 'filladapt)
(vendor 'coffee-mode)
(vendor 'haml-mode)
(vendor 'sass-mode)
(vendor 'htmlize)
(vendor 'ack-and-a-half 'ack-and-a-half 'ack-and-a-half-same 'ack-and-a-half-find-file 'ack-and-a-half-find-file-same 'ack-and-a-half-interactive)
(vendor 'magit         'magit-status)
(vendor 'psvn          'svn-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode 'gfm-mode)
(vendor 'textile-mode  'textile-mode)
(vendor 'csv-mode      'csv-mode)
(vendor 'yaml-mode     'yaml-mode)
(vendor 'rcodetools    'xmp)
(vendor 'dropdown-list) ;; Needed before yasnippet
(vendor 'yasnippet)
(vendor 'jekyll)
(vendor 'lua-mode      'lua-mode)
(vendor 'feature-mode)
(vendor 'mode-line-bell)
(vendor 'revbufs       'revbufs)
(vendor 'shell-pop)
(vendor 'mo-git-blame  'mo-git-blame-file 'mo-git-blame-current)
(vendor 'ace-jump-mode 'ace-jump-mode 'ace-jump-word-mode 'ace-jump-char-mode 'ace-jump-line-mode)
(vendor 'key-chord)
(vendor 'bundler       'bundle-open 'bundle-console 'bundle-install 'bundle-update 'bundle-check)
(vendor 'browse-kill-ring+ 'browse-kill-ring)
(vendor 'browse-kill-ring  'NEVERLOAD-browse-kill-ring)
(vendor 'dired-details 'dired-details-show 'dired-details-hide 'dired-details-toggle)
(vendor 'dired-details+)
(vendor 'powerline)

;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)

;; Load user specific emacs customize settings --------------------------------
(setq custom-file (concat user-path "/custom.el"))
(load custom-file 'noerror)
